[language-server.biome]
command = "biome"
args = ["lsp-proxy"]
config = { provideFormatter = true }
display-messages = true
required-root-patterns = ["*.ts", "*.tsx", "*.js", "*.jsx", "*.mts", "package.json", "tsconfig.*"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.json]
command = "vscode-json-languageserver"

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
roots = ["tailwind.config.js", "mix.exs"]
config.tailwindCSS.includeLanguages = {heex = "html", elixir = "html"}

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.rescript]
command="rescript-language-server"
args=["--stdio"]

[language-server.pyright.config]
python.analysis.lint = true
python.analysis.inlayHint.enable = true
python.analysis.autoSearchPaths = true
python.analysis.diagnosticMode = "workspace"
python.analysis.useLibraryCodeForType = true
python.analysis.logLevel = "Error"
python.analysis.typeCheckingMode = "basic"
python.analysis.autoImportCompletion = true

[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "elixir"
roots = ["mix.exs"]
auto-format = true
language-servers = [ "elixir-ls", "tailwindcss-ls" ]

[[language]]
name = "heex"
language-servers = [ "elixir-ls", "tailwindcss-ls", "vscode-html-language-server" ]
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json", "requirements.txt"]

[[language]]
name = "markdown"
language-servers = ["harper-ls"]

[[language]]
name = "javascript"
file-types = [{glob = "**/!(*.res).{js,mjs}"}]
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "html"
language-servers = ["tailwindcss-ls", { name = "superhtml", except-features = ["format"] }, "vscode-html-language-server"]
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name="typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "emmet-ls"]
auto-format = true
roots = ["package.json"]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path=prd.ts",
] }

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "rescript"
scope = "source.rescript"
language-servers=[{name="rescript"}]
roots = ["rescript.json"]
auto-format = true
comment-token = "//"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"

